# Generated by Django 3.2.3 on 2021-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=100)),
                ('password1', models.CharField(max_length=45)),
                ('password2', models.CharField(max_length=45)),
            ],
        ),
    ]
