# Generated by Django 3.2.3 on 2021-06-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Krishi_Pradhan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accounts',
            new_name='User',
        ),
    ]
