# Generated by Django 3.2.3 on 2021-07-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krishi_Pradhan', '0002_rename_accounts_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='crop_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region1', models.CharField(max_length=255)),
                ('soil1', models.CharField(max_length=255)),
                ('crop1', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('soil', models.CharField(max_length=100)),
                ('previous', models.CharField(max_length=100)),
            ],
        ),
    ]
