# Generated by Django 3.2.3 on 2021-07-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Krishi_Pradhan', '0003_crop_data_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crop_data',
            new_name='cropdata',
        ),
    ]
