# Generated by Django 3.2.3 on 2021-07-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Krishi_Pradhan', '0004_rename_crop_data_cropdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cropdata',
        ),
    ]
