# Generated by Django 5.0.dev20230916185426 on 2024-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krishi_Pradhan', '0007_alter_cropdata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdata',
            name='crop1',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='region1',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='soil1',
        ),
        migrations.AddField(
            model_name='cropdata',
            name='previous',
            field=models.CharField(choices=[('wheat', 'Wheat'), ('corn', 'Corn'), ('rice', 'Rice'), ('soybean', 'Soybean')], default='True', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropdata',
            name='region',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropdata',
            name='soil',
            field=models.CharField(choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('loam', 'Loam'), ('silt', 'Silt')], default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
